### ISSUE TITLE
FTRE - 4 - Disponibilização do servico frontend

### ISSUE THREAD

**Issue by marcus-vinf** [vinicius-escano/plataforma-conscientiza-frontend#1]
**Feature para construir a API frontend que mostrará informações e se comunicará com o backend**

_Ao ser fisgado por uma das metodologias de abordagem, o usuário deverá ser redirecionado a uma página de "boas vindas", que deverá explicar o que está acontecendo, ou seja, que a 'vitima' quase caiu em um golpe, mas que a plataforma vai ajuda-la a não cometer os mesmos erros que levaram ela a cair em golpes novamente._

Os objetivos para construção do frontend são:
- [x] Definir esquema de cores
- [x] Gerar os fontes da entidade registro
- [x] Definir mensagem de apresentação
- [x] Definir fontes de texto - (Poderá sofrer alterações)
- [x] Criar a página principal que receberá o usuário. 

_A tela deve conter uma mensagem amigável de que o usuário participou de um ‘teste’ e em seguida mostrar os dados referentes a pesquisa como meio de conscientização. A página não deve ser grande, o tema de cores deverá ser azul / verde e paletas semelhantes._

**Sugestão de componentes da tela**
- Exibir um aviso sobre a ação em que a "vitima" está participando
- Mostrar uma janela com o vídeo informativo da campanha
- Relacionar links dos infográficos da análise de dados coletados (Criar o link, a tela será tratada na FRTE-5)
- Footer com informações do projeto, contato e afins

Utilizar esquema de cores que transmita tranquilidade ao usuário, segue sugestão analisada por IA
Prompt: "Mostre paletas de cores que transmitem tranquilidade e confiança"
- Tons de Azul
Azul Claro: Transmite calma e confiança.
Azul Turquesa: Um pouco mais vibrante, mas ainda suave e relaxante.

- Verde Suave
Verde Menta: Remete à natureza e frescor, trazendo uma sensação de paz.
Verde Pastel: Cria um ambiente tranquilo e acolhedor.

- Tons de Lavanda
Azul Claro + Cinza Claro: Uma paleta fresca e tranquila.
Verde Menta + Bege: Uma combinação suave e convidativa.

----------------------------
Critérios de aceite:
- Projeto funcional (Poder ser utilizado sem complicações"
- Requisitos finalizados
- Issue no pronto

**Comment by vinicius-escano** [comment]
O serviço está funcionando com as seguintes configurações
![Image](https://github.com/user-attachments/assets/ac3592bd-e396-4507-8b06-99ab18127162)

Para acessar a página inicial deve-se utilizar o endereço [Frontend](http://localhost:4200) 

A página inicial carregada é apresentada abaixo (Os dados apresentados foram gerados por IA somente para definir disposição dos itens)
![Image](https://github.com/user-attachments/assets/398c5b76-4f85-4b99-b5db-bf9c67fe6b4e)

A partir desse ponto, deve-se implementar as funcionalidades nos arquivos:

- Component: "src/app/registry/registry-component.ts"
- Layout: "src/app/registry/registry-component.html"
- Service: "src/app/registry/registry-service.ts"
- Model: "src/app/registry/registry-model.ts"
- Estilos: "src/app/registry/registry-component.css"
![Image](https://github.com/user-attachments/assets/cb7c7cb0-f0ef-456a-b0bd-b23600b1a617)

**Comment by vinicius-escano** [comment]
**Sobre as cores definidas**

A primeiro momento será utilizado cores de tons verde / azul a fim de trazer tranquilidade ao usuário apesar de informar que a pessoa quase foi uma vitima de golpe

**Comment by vinicius-escano** [comment]
Commit da estrutura inicial: [FTRE-4](https://github.com/vinicius-escano/plataforma-conscientiza-frontend/commit/c39a7244379bc5b6caf0b21c8abd105b481662be)

**Comment by davifma** [comment]
Precisa rever essa tipografia
![Image](https://github.com/user-attachments/assets/c3411c6b-1ab0-4d93-8dd1-27d0591537e7)

Onde está a documentação referente a interface?

**Comment by vinicius-escano** [comment]
Tipografia ainda poderá ser revista.
A documentação da interface ainda não foi disponibilizada pela interface ainda não estar definida/finalizada, entretanto colocamos como informativo a estrutura e arquivos para serem implementados conforme [comentário ](https://github.com/vinicius-escano/plataforma-conscientiza-frontend/issues/1#issuecomment-2383950858)

**Comment by davifma** [comment]
Quais são os requisitos que devem ser finalizados?

**Comment by vinicius-escano** [comment]
Serviço disponibilizado no link [Plataforma](https://plataforma-conscientiza.vercel.app)

- Desconsiderar video, usado somente para desenvolvimento da página, será colocado um própio para o assunto
- A página de analises ainda está em construção
