### ISSUE TITLE
FTRE - 5 - Página de análise

### ISSUE THREAD

**Issue by vinicius-escano** [vinicius-escano/plataforma-conscientiza-frontend#16]
Disponibilizar uma página de análise dos dados obtidos.

Elaborar uma página de preferência com gráficos para mostrar os dados coletados, a fim de análise e informação para o usuário.

A pagina deve conter as informações:

- Total de acessos
- Tipo de aparelhos usados para o acesso
- Origem de acesso

- [x] Buscar componentes de gráficos para uso na tela
- [x] Analisar melhor layout de gráfico
- [x] Definir background com o tema azul e verde
- [x] Montar um gráfico com as informações listadas
- [x] Implementar filtros dinâmicos

Critérios de aceite:

- Projeto funcional (Poder ser compilado e utilizado sem complicações)
- Requisitos finalizados
- Issue no pronto

**Comment by vinicius-escano** [comment]
Seria interessante utilizar gráficos nessa página de análise. O angular proporciona alguns modelos prontos que podem ser utilizados, abaixo seguem sugestões de designs

[Modelos Gráficos (PrimeNG)](https://primeng.org/chart)

Tipo Barras
![Image](https://github.com/user-attachments/assets/63802a3f-33a9-4ae5-86f0-ff6bcb9c98db)

Tipo Pizza
![Image](https://github.com/user-attachments/assets/77e31838-396e-4fd0-aa7a-a80a28d79a79)

Tipo Onda ( Poderia ser utilizado para fazer uma relação tempo x acessos
![Image](https://github.com/user-attachments/assets/d591339a-d19b-404a-89f6-1d5ae3b45568)

**Comment by davifma** [comment]
Qual a relação dos navegadores que realizaram o acesso na página com o valor proposto por vocês de conscientizar sobre golpes?

**Comment by vinicius-escano** [comment]
> Qual a relação dos navegadores que realizaram o acesso na página com o valor proposto por vocês de conscientizar sobre golpes?

De fato não tem muito valor ao usuário, mas pensando em uma aplicação prática, sabendo quais são os navegadores mais utilizados podemos notificar as empresas para procurar soluções para ajudar o usuário a identificar golpes ou informar ao publico qual navegador poderia ser melhor para utilizar.
Fora as empresas, a própria comunidade de desenvolvedores podem criar ferramentas para identificar sites com chamarizes maliciosos como os plugins de navegadores.

**Comment by davifma** [comment]
Pelo menos aqui parece que a análise está acontecendo.

**Comment by vinicius-escano** [comment]
Documentação de implementação

Uso dos componentes; 
Importar os pacotes ReactiveFormsModule e CommonModule.
![Image](https://github.com/user-attachments/assets/9e8b667c-9ca2-4573-af57-e8a122ae79fa)

No arquivo responsável pelo componente da tela, informar também na guia imports
![Image](https://github.com/user-attachments/assets/30e024bd-0d6f-4c32-8dfb-f1827ed7619e)

Disposição em tela:
Declarar no arquivo de layout o seguinte componente
![Image](https://github.com/user-attachments/assets/0bdba520-edc1-46f7-9c10-f688aac73aa9)
sendo type = tipo de gráfico / width e height = dimensões do gráfico / data = dados a serem exibidos / options = opções do gráfico

Utilizar a classe api-service para trazer os dados do backend
![Image](https://github.com/user-attachments/assets/c1c514cc-ac72-4059-a897-22209b8b3242)
