### ISSUE TITLE
FTRE - 9 - Disponibilizar as páginas com guias e artigos

### ISSUE THREAD

**Issue by vinicius-escano** [vinicius-escano/plataforma-conscientiza-frontend#17]
Ao analisar o conteúdo da primeira página da aplicação, percebemos que mais conteúdo pode ser inserido com links que direcionam para outras páginas que tratarão de assuntos para conscientizar o usuário com relação aos golpes online.

Assuntos:
1 - Quais são os golpes mais comuns
2 - Como observar as pistas de um anuncio, mensagem ou ligação falsa / Comportamentos e padrões de ações
3 - Canais de denuncia e o que fazer ao ser vítima de um golpe ou tentativa do mesmo

Nesses 3 assuntos consideramos que estamos abordando o problema, como se prevenir contra o golpe e o que fazer caso a pessoa seja vítima de um.
Para criar o conteúdo de cada página, pode ser levado em consideração os estudos realizados e compilados no documento de descrição do projeto.

Objetivos

- [x]  Página 1: Quais os golpes mais comuns.
      - [x] Criar o conteúdo
      - [ ] Disponibilizar em um modelo de página
      - [x] Inserir ícone com caminho da página
- [ ]  Página 2: Como observar as pistas e padrões.
      - [x] Criar o conteúdo
      - [x] Disponibilizar em um modelo de página
      - [x] Inserir ícone com caminho da página
- [ ]  Página 3: O que fazer ao sofrer um golpe.
      - [x] Criar o conteúdo
      - [x] Disponibilizar em um modelo de página
      - [x] Inserir ícone com caminho da página

**Comment by vinicius-escano** [comment]
Conteúdo Página 1:
--

**Phishing e suas variantes**

O termo Phishing pode ser associado como uma pescaria, trata-se de jogar "iscas" por diferentes métodos, esperando que a vítima seja fisgada pela curiosidade, medo ou ganância.

**Como funciona:** O golpista envia e-mails, mensagens de texto ou até mesmo mensagens em redes sociais se passando por uma instituição confiável (bancos, empresas de serviços, etc.) para coletar informações pessoais, como senhas, números de cartão de crédito ou dados bancários. Esse é o tipo mais comum de abordagem para realizar um golpe, pois muitas vezes uma simples mensagem se passando por alguém já é suficiente para ganhar a confiança da vítima.

**Exemplo:** Um e-mail falso que parece ser de um banco pedindo para "verificar sua conta" e inserir dados confidenciais em um site falso.

Além do phishing, existem algumas denominações para abordagens mais específicas como o **Vishing (Voice Phishing)**, que são abordagens realizadas por telefone em que o golpista se passa por uma instituição confiável, como banco ou empresa, para coletar dados confidenciais. E também o **Smishing (SMS Phishing)**, que tem o mesmo objetivo, mas a abordagem é feita por mensagens SMS ou aplicativos como WhatsApp e outros.

---

**Clonagem de Cartão**

**Como funciona:** O criminoso captura os dados do cartão de crédito ou débito da vítima e realiza transações fraudulentas.

**Exemplo:** Um site falso pede informações de pagamento e as utiliza para realizar compras sem a autorização da vítima.

---

**Furto de Identidade**

**Como funciona:** Os criminosos coletam dados pessoais da vítima (nome, CPF, endereço, etc.) para abrir contas em seu nome ou realizar transações financeiras.

**Exemplo:** Um criminoso obtém informações pessoais através de phishing ou vazamentos de dados e usa para abrir uma linha de crédito ou fazer empréstimos.

---

**Golpes em Redes Sociais**

**Como funciona:** Os criminosos se aproveitam das redes sociais para enganar os usuários, seja por meio de perfis falsos, sorteios fraudulentos ou promoções falsas.

**Exemplo:** Um link em uma rede social promete um prêmio, mas ao ser clicado, solicita dados pessoais ou direciona para um site falso que instala malware.

---

**Softwares maliciosos**

Softwares (ou "programas de computador") maliciosos, também conhecidos como malware, podem ser usados para atingir e criptografar dados e arquivos em um dispositivo, além de promover acessos para hackers invadirem um sistema, assim podendo controlar um dispositivo remotamente e ter acesso a recursos como microfone e câmera. Exemplos desses softwares são os Ransomwares, Scarewares e Spywares.

---

**Ransomware**

**Como funciona:** Um software, normalmente conhecido como "programa de computador" malicioso, é instalado no dispositivo da vítima e criptografa seus arquivos, tornando-os inacessíveis. O criminoso exige um pagamento em criptomoeda para liberar os arquivos.

**Exemplo:** Um pop-up aparece no computador avisando que seus arquivos estão bloqueados, e só será possível desbloqueá-los após pagar um resgate em Bitcoin.

---

**Scareware**

**Como funciona:** O criminoso cria um alerta falso, geralmente dizendo que o dispositivo da vítima está infectado por vírus, e oferece um software para "consertar" o problema, que na verdade é um malware.

**Exemplo:** Um pop-up aparece dizendo que o computador está cheio de vírus e oferece um download "necessário" para eliminar os supostos problemas, mas na realidade instala malware.

---

**Spyware**

**Como funciona:** Softwares maliciosos são instalados no dispositivo da vítima, sem o seu conhecimento, com o objetivo de roubar informações, monitorar atividades ou danificar sistemas.

**Exemplo:** Um aplicativo malicioso que coleta informações de navegação, senhas ou até mesmo ativa a câmera do dispositivo sem a permissão do usuário.

---

**Fraude em Compras Online**

**Como funciona:** Sites falsos ou de terceiros comprometidos oferecem produtos a preços atrativos, mas após o pagamento, o produto não é enviado ou a mercadoria recebida é diferente do anunciado.

**Exemplo:** Comprar um item muito barato em um site desconhecido e nunca receber o produto ou receber algo de qualidade inferior.

---

**Golpes de Investimento**

**Como funciona:** O golpista se faz passar por um "especialista em investimentos" e convence a vítima a investir dinheiro em esquemas fraudulentos, como criptomoedas ou ações que não existem.

**Exemplo:** Um e-mail ou mensagem em redes sociais promete retornos altíssimos com investimentos em criptomoedas, mas na verdade é uma armadilha para roubo de dinheiro.

---

**Comment by vinicius-escano** [comment]
Conteúdo da página 2: 
--

A internet, sem dúvida, trouxe inúmeras facilidades para o nosso dia a dia, como o acesso instantâneo a informações, compras, serviços bancários e comunicação global. Contudo, ela também se tornou um terreno fértil para a atuação de criminosos virtuais. Os golpes online são uma ameaça crescente e, muitas vezes, os golpistas se aproveitam da ingenuidade, da pressa ou da confiança das pessoas para aplicar fraudes. Portanto, é fundamental desenvolver a habilidade de identificar sinais de golpes online, a fim de se proteger contra prejuízos financeiros e danos à segurança pessoal.

Aqui reunimos algumas dicas e pontos a se atentar sempre que receber aquele email suspeito, ou quando algum conhecido manda uma mensagem falando que trocou de número e precisa de um dinheiro emprestado e até mesmo o banco te ligando falando de uma compra não autorizada. Veja abaixo o que você deve prestar atenção antes de fazer qualquer coisa que o possível golpista esteja te pedindo.

---

**Atenção aos E-mails e Mensagens Suspeitas**

Um dos primeiros sinais de golpe online são e-mails ou mensagens suspeitas. Os golpistas frequentemente se passam por empresas confiáveis, como bancos, redes de lojas e serviços online, solicitando que a vítima clique em links ou forneça informações pessoais. Eles podem usar frases como "Sua conta foi comprometida", "Ação urgente necessária" ou "Clique aqui para confirmar sua identidade". Esses e-mails geralmente apresentam erros de português, um tom apressado e links que levam a sites falsificados.

Antes de clicar em links ou baixar anexos, verifique o remetente, confirme a autenticidade da mensagem através de canais oficiais (como ligar para o banco, por exemplo) e observe sinais de fraudes, como erros de português ou URLs suspeitas.

Procure também saber como é o comportamento de uma instituição ou pessoa que por ventura venha te abordar. Por exemplo, os bancos quase nunca irão ligar para você, a não ser em algum caso realmente estranho, e mesmo assim, a instituição não pede que você confirme seus dados por telefone. O certo em caso de operações bancárias é o usuário ligar para o banco ou até mesmo ir pessoalmente para garantir que a situação é real. Outro exemplo é sempre que receber uma mensagem de alguma pessoa conhecida, mas que tem um número diferente ou pedindo algo estranho, tente fazer uma chamada telefônica ou de vídeo com a pessoa. Caso ela se recuse, é um forte sinal de que pode ser um golpista se passando por outra pessoa. E sempre que for fazer uma transferência de dinheiro como o PIX, verifique os dados antes de concluir a transação.

---

**Sites falsos e links duvidosos**

Os criminosos frequentemente criam sites falsos que imitam os de empresas confiáveis, como lojas virtuais ou instituições financeiras. Esses sites fraudulentos podem oferecer promoções irresistíveis ou exigir que o usuário insira dados sensíveis, como números de cartão de crédito e informações bancárias.

Para identificar se um site é verdadeiro ou falso, observe o seguinte:

- **URL:** Verifique se o endereço começa com "https://" e se há um ícone de cadeado próximo ao link. Embora não seja uma garantia absoluta de segurança, esses detalhes são importantes.
- **Erros de digitação:** Sites fraudulentos muitas vezes possuem erros de digitação ou um design de baixa qualidade, que não corresponde ao padrão da empresa original.
- **Pesquise a reputação do site:** Busque avaliações e comentários de outros usuários antes de realizar compras ou fornecer dados pessoais. Ferramentas como o Google e sites de reputação como o Reclame Aqui podem ajudar a verificar a autenticidade de um site.

---

**Ofertas ou Promoções Irresistíveis**

Quando algo parece bom demais para ser verdade, é porque geralmente não é. Golpes como fraudes de e-commerce e promoções falsas muitas vezes aparecem como ofertas imperdíveis: descontos absurdos, prêmios, sorteios ou produtos de alta demanda a preços abaixo do mercado. Esses métodos são comuns em golpes de "shopping online" e podem ser usados para induzir as vítimas a fornecerem dados de pagamento ou realizarem transações em sites falsificados.

Em situações como essa, é importante:

- **Verificar a procedência:** Antes de realizar uma compra, confirme se o vendedor é confiável e se a promoção é legítima.
- **Evitar decisões impulsivas:** Golpistas costumam explorar a sensação de urgência. Se você sentir pressa, desconfie.
- **Pesquisar o produto ou serviço:** Uma pesquisa rápida sobre a empresa ou oferta pode revelar se há reclamações de outros consumidores ou se o site está associado a fraudes.

---

**Solicitação de dados pessoais**

Empresas confiáveis nunca pedem informações sensíveis, como números de CPF, senha, ou dados bancários via e-mail ou mensagem.

Se algo parecer suspeito, encerre o contato com a suposta instituição e entre em contato diretamente com a empresa através dos números oficiais fornecidos através de um site ou o que está atrás do cartão de crédito para confirmar a veracidade da solicitação. Procure sempre estabelecer um contato de duas vias; além de ser informado pela empresa de alguma situação irregular que requer dados, tente saber mais sobre a solicitação.

Por fim, o que vale é estar informado de como os criminosos agem e sempre desconfiar ao ser contatado por alguém ou alguma instituição que ofereça algo bom demais para ser verdade, pedindo informações sensíveis ou solicitando códigos de acesso (tokens). Se por algum momento você ficar em dúvida da veracidade do contato, procure os canais oficiais da instituição e, se for outra pessoa se passando por alguém que você conheça, tente confirmar que a pessoa com quem você está falando seja a verdadeira. Ajude as autoridades a impedir as atividades criminosas realizando denúncias através dos links disponibilizados AQUI.

---

**Comment by vinicius-escano** [comment]
Conteúdo da página 3:
--

Denunciar tentativas de golpe é fundamental para proteger outras pessoas e ajudar a combater crimes digitais. No Brasil, há vários canais oficiais para denunciar fraudes e golpes online, além de manter a comunicação com a comunidade para conscientizar outras pessoas. Aqui estão os principais canais de denúncia:

---

**Polícia Civil**

O método mais tradicional de denúncia é abrir um boletim de ocorrência em uma delegacia. Além dos locais físicos, a denúncia pode ser feita pelos telefones:

**Polícia Civil: 197**  
**Disque Denúncia: 181**

Também pode ser feita pelos sites, porém, cada estado tem sua página de denúncia. Para encontrar, pesquise no Google algo como "site da polícia civil de [seu estado]".

---

**Procon**

Caso o golpe envolva empresas ou produtos fraudulentos, você pode registrar uma reclamação junto ao Procon. Ele também atua em casos de serviços ou produtos que não foram entregues conforme prometido.

**Denúncia Online:** Acesse o site do Procon do seu estado ou município e siga as instruções para registrar a denúncia.

---

**Denunciar no site "Denúncia de Fraudes da Internet"**

O "Denúncia de Fraudes da Internet" é um site de utilidade pública onde é possível registrar fraudes online. Acesse: [denuncie.org.br](https://www.denuncie.org.br)

Nesse link, você pode denunciar sites falsos, e-mails fraudulentos e outras tentativas de golpe pela internet de uma forma simples.

---

**Grupos de redes sociais e sites de reviews**

Além dos métodos legais para realizar uma denúncia, pode ser muito eficaz ajudar a espalhar a informação para que mais pessoas fiquem atentas e evitem cair no mesmo golpe. Você pode usar os grupos e comunidades das redes sociais ou então sites de review como o [Reclame Aqui](https://www.reclameaqui.com.br), assim, antes de comprar algo ou responder uma mensagem, as pessoas podem pesquisar casos semelhantes.

---

**Comment by davifma** [comment]
Onde estão os dados que apoiam essas afirmações?
